services:
  ollama:
    image: ollama/ollama:0.5.4
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11435:11434"  #expose port 11434 on container
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=-1h

volumes:
  ollama:
