defaults:
  - _self_
  - /common_ai/llm@llm: ollama.yaml
  - /common_ai/embeddings@embeddings: ollama.yaml
  - /common_ai/textsplitter@textsplitter: standard.yaml
  - /common_ai/vectorstore@vectorstore: chroma.yaml
