# requires AZURE_OPENAI_API_KEY and AZURE_OPENAI_ENDPOINT to be set as environment variables
llm:
  _target_: langchain_openai.AzureChatOpenAI
  deployment_name: use4o
  openai_api_version: 2024-10-21
embeddings:
  _target_: langchain_openai.AzureOpenAIEmbeddings
  deployment: initialAda002
  openai_api_version: 2024-10-21
