home: ${oc.env:HOME,null}

paths:
  composer_home: ${config.home}/.composer-core
  composer_data: ${config.paths.composer_home}/data
  composer_logs: ${config.paths.composer_home}/logs

# Open AI API info
llm_config:
  openai:
    api_key: null
    llm: gpt-4o-mini
    embedding: null
