obj:
  _target_: composer.protocol.grantgist.GrantGistSync
  _partial_: true

config:
  filename: GrantsDBExtract${today}v2
  url_base: "https://prod-grants-gov-chatbot.s3.amazonaws.com/extracts"

defaults:
  - _self_
  - /_internal/grantgist@config: common-config.yaml
