targets:
  pull_grants_gov_extract:
    _target_: composer.protocol.grantgist.pull_grants_gov_extract
    _partial_: true
  pull_details:
    _target_: composer.protocol.grantgist.pull_details
    _partial_: true
  pull_pdfs:
    _target_: composer.protocol.grantgist.pull_pdfs
    _partial_: true

config:

  # The home directory for grantgist
  root: ${paths.home}/grantgist

  # Filename pattern
  extracts_filename: GrantsDBExtract${today}v2

  # Urls required by the various grantgist API requests
  urls:
    download: "https://apply07.grants.gov/grantsws/rest/opportunity/att/download"
    details: "https://apply07.grants.gov/grantsws/rest/opportunity/details"
    extracts: "https://prod-grants-gov-chatbot.s3.amazonaws.com/extracts"

  min_date: ${today}
  max_date: ${today}

defaults:
  - _self_
  - /ai/llm@config.llm: ollama.yaml 
  - /ai/embeddings@config.embeddings: ollama.yaml
  - /ai/vectorstore@config.vectorstore: chroma.yaml
