targets:
  pull_grants_gov_extract:
    _target_: composer.protocol.grantgist.pull_grants_gov_extract
    _partial_: true
  pull_details:
    _target_: composer.protocol.grantgist.pull_details
    _partial_: true
  pull_pdfs:
    _target_: composer.protocol.grantgist.pull_pdfs
    _partial_: true
  construct_vectorstore:
    _target_: composer.protocol.grantgist.construct_vectorstore
    _partial_: true

config:

  # The home directory for grantgist
  root: ${paths.home}/grantgist

  # Filename pattern
  extracts_filename: GrantsDBExtract${today}v2

  # Urls required by the various grantgist API requests
  urls:
    download: "https://apply07.grants.gov/grantsws/rest/opportunity/att/download"
    details: "https://apply07.grants.gov/grantsws/rest/opportunity/details"
    extracts: "https://prod-grants-gov-chatbot.s3.amazonaws.com/extracts"

  min_date: ${today}
  max_date: ${today}

  retriever_kwargs: 
    search_kwargs:

      # The number of documents to retrieve for each question
      k: 10

      # Filters to apply to each search. For example, filtering by the
      # office of science:
      filter:
        AgencyName: "Office of Science"

  # Chunks the calls to the embedding model so as to not overwhelm it with
  # too many requests at once
  max_docs_per_embedding_call: 500

  # Disqualifies documents that contain the following strings:
  disqualifying_strings:

    # Disqualifies pdfs which require a certain version of adobe to load
    - "The document you are trying to load requires Adobe Reader 8 or higher"
